version: '3'
services:
    web:
      build: .
      volumes:
        - .:/trails-diary
      ports:
        - 4000:80
      depends_on:
        - db
      env_file:
        - .env
    db:
      image: postgres:12.0-alpine
      volumes:
        - trails-db:/var/lib/postgresql/data
volumes:
  trails-db:
