version: '3'
services:
    web:
      build: .
      container-name: trails_diary_web
      volumes:
        - .:/trails-diary
      ports:
        - 3000:3000
      depends_on:
        - db
      env_file:
        - .docker.env
    db:
      image: postgres:12.0-alpine
      container-name: trails_diary_db
      volumes:
        - trails-db:/var/lib/postgresql/data
volumes:
  trails-db:
