version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Rubocop ok?
          command: bundle exec rubocop --config .rubocop.yml
      - run:
          name: tests ok?
          command: RAILS_ENV=test bundle exec rake db:test:prepare
          command: bundle exec rspec
      - run:
          name: Gems ok?
          command: bundle-audit check --update
          command: ruby/bundle-install
