  default: &default 
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: <%= ENV.fetch("POSTGRES_USERNAME") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
    host: <%= ENV.fetch("DATABASE_HOST_URL") %>

  development:
    <<: *default
    database: trails_diary_development

  test:
    <<: *default
    database: trails_diary_test

  production:
    <<: *default
    database: trails_diary_production
